name: code examples
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch:
  schedule:
    - cron: '59 23 * * *'
jobs:
  run-code_examples-tests:
    runs-on: ubuntu-latest
    name: Playwright testing code examples
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies with Playwright
        run: |
          pnpm playwright install --with-deps

      - name: Run tests
        run: npx playwright test checkCodeExamples.spec.ts --project=chromium
