name: code examples
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch:
  schedule:
    - cron: '59 23 * * *'
jobs:
  run-code_examples-tests:
    runs-on: ubuntu-latest
    name: Playwright testing code examples
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm install -D @playwright/test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Run tests
        run: npx playwright test checkCodeExamples.spec.ts --project=chromium
