name: e2e

on: 
    workflow_dispatch:
    schedule:
      - cron: '59 23 * * *'

jobs:
  run-e2e:
    name: Playwright testing demo
    runs-on: macos-14
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: corepack enable
      - run: pnpm --version
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"
      - name: install
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Install dependencies with Playwright
        run: |
          pnpm playwright install --with-deps
      - name: Run tests
        run: pnpm run test:e2e
        env:
          BASE_E2E_URL: https://frontends-demo.vercel.app/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: reports
          path: apps/e2e-tests/reports/
          retention-days: 7