name: Lighthouse CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch:
  schedule:
    - cron: '59 23 * * *'
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            "https://frontends-demo.vercel.app/"
          uploadArtifacts: true 
          temporaryPublicStorage: true
          configPath: './lighthouserc.js'
      - run: npm install && npm install -g @lhci/cli@0.11.x
      - run: npm run build
      - run: lhci autorun

