name: Visual Tests

on: 
  workflow_dispatch:
  schedule:
    - cron: '59 23 * * *'

jobs:
  run-e2e:
    name: Playwright visual test demo
    runs-on: macos-14
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 10

      - name: Test
        run: npx playwright test -c visual.config.ts visual-tests.spec.ts --project=chromium --ignore-snapshots
