name: Vue Blank
run-name: Playwright is testing vue blank 🚀
on: 
  workflow_dispatch:
  schedule:
    - cron: '59 23 * * *'
jobs:
  run-code_examples-tests:
    runs-on: ubuntu-latest
    name: Playwright testing code examples
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Run tests
        run: BASE_E2E_URL=https://stackblitz.com/github/shopware/frontends/tree/main/templates/vue-blank npx playwright test checkStackblitzTemplates.spec.ts --project=chromium
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
            {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
            }
            }
            ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK    
    
